version: 2
jobs:
    build:
        working_directory: ~/blueditor
        docker:
            - image: circleci/python:3.12
        steps:
            - checkout
            - run:
                  name: addFlake8
                  command: sudo pip install flake8
            - run:
                  name: pep8Check
                  command: sudo flake8 --max-complexity 10
